pipeline {
    agent any


    stages {
        stage('Build') {
            steps {
                git 'https://github.com/hwchiu/netutils.git'

                sh "docker build ."

            }

            post {
                success {
                    echo "hello world"
                }
            }
        }
    }
}

